steps:
  - script: |
      . build/set_pipeline_variables.sh
    displayName: 'Set pipeline variables'
  - script: |
      . build/build_docker.sh
    displayName: 'Build Docker image'
  - task: Docker@2
    displayName: Login to ACR
    inputs:
      command: login
      containerRegistry: stratsysContainerRegistry
  - script: |
      . build/push_dockerimage.sh
    displayName: 'Push Docker image'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  - script: |
      . build/update_playbook.sh
    displayName: 'Update playbook'
  - task: Docker@2
    displayName: Logout from ACR
    inputs:
      command: logout
      containerRegistry: stratsysContainerRegistry
  - script: |
      . build/remove_dockerimage.sh
    displayName: 'Remove built image'
variables:
  - name: RELEASE_BRANCH
    value: $(Build.SourceBranchName)
  - name: COMPLETE_RELEASE_BRANCH
    value: $(Build.SourceBranch)
  - name: GIT_COMMIT_SHA
    value: $(Build.SourceVersion)
  - group: "Azure container registry - stratsys"
  - group: "Github-Playbook"
trigger:
  - master
pool: "Linux-docker"
